server:
  port: 9001
  shutdown: graceful
  tomcat:
    threads:
      min-spare: 5
      max: 50
    keep-alive-timeout: 15s
    connection-timeout: 2s

spring:
  application:
    name: catalog-service
  profiles:
    active: datatest
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstoredb_catalog
    username: user
    password: password
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bookstore
  data:
    rest:
      default-page-size: 10
  cloud:
    function:
      definition: reduceInventory
    stream:
      bindings:
        reduceInventory-in-0:
          destination: inventory-reduced
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

# Info system
info:
  system: Bookstore system

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: info, health, env, flyway, loggers, mappings, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

bookstore:
  cloudinary:
    cloud-name: dl0v8gbku
    api-key: 862736244281148
    api-secret: XuPt3no_rU3T5_fz_dCd5dhvOqo
