spring:
  datasource:
    url: jdbc:postgresql://bookstore-postgres/bookstoredb_catalog
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://bookstore-keycloak/realms/bookstore